name: Push to master
on:
  push:
    branches:
      - master
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Cache dependencies
        id: cache-deps
        uses: actions/cache@v3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts
    
  build:
    name: Run tsc
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: yarn build
    
  lint:
    name: Run linting
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: yarn lint
  
  test:
    name: Run testing
    runs-on: ubuntu-latest
    needs: [setup]
    steps:
      - run: yarn test --passWithNoTests
      
  publish:
    name: Publish to npm
    runs-on: ubuntu-latest
    needs: [build, lint, test]
    steps: 
      - name: Publish to NPM
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
          access: public
  
  release:
    name: Tag & Release
    runs-on: ubuntu-latest
    needs: [publish]
    steps:       
      - name: Extract version from package.json
        id: extract_version
        uses: Saionaro/extract-package-version@v1.1.1

      - name: Create release on github
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GH_TOKEN }}
          prerelease: false
          title: v${{ steps.extract_version.outputs.version }}
          automatic_release_tag: v${{ steps.extract_version.outputs.version }}
